### PR TITLE
[DONE] update anaimated layer and style

### PR DESCRIPTION
**Pull request by woutervanesse**
Updated animated discharge layers to display actual values instead
absolute.
Added new style for discharge with absolute values and arrows.
Added new style for node waterlevel diff that shows negative values as
well.

### CODE REVIEW

**Comment by jackieleng** [comment]
Cool feature, but it's giving really weird line_results for me:
non absolute animation

**Comment by woutervanesse** [comment]
OK, Are you on a miniature scale with your model? The size of the arrows is in meters, I believe 2 meters for the scale visible on your screen. I picked them based on the scale of a typical model of a polder.

Try these results: I:\Data_Sources\work\W_vEsse\test\sturing_hhw

**Comment by jackieleng** [comment]
No, a relatively normal zoom. Maybe there are very big/small values in the NetCDF?

**Comment by woutervanesse** [comment]
no I think you are one wgs84 while the style assumes meters for the size of the arrows. Can you try to switch to RD?

**Comment by woutervanesse** [comment]
Is this a problem? I can make the arrow sizes more realtive (not in meters)

**Comment by jackieleng** [comment]
Yes, that was the problem, switching to RD does the trick. But if you can make it work for both RD and wgs84, that would be nice I think.

Another thing I noticed: the colors for both positive and negative values are the same. Is that intended? Now you can't see what's what, or is that not a problem?

**Comment by woutervanesse** [comment]
Fixed relative size of arrows and made rendering quicker

**Comment by jackieleng** [comment]
Very nice.

**Comment by jackieleng** [comment]
I added an entry for the changes for you. Besides that, it's good to go.

**Pull request merged**
